name: e-redes-smart-metering-plus-dev

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.1.0
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
    environment:
      TZ: Europe/Lisbon
      PYTHONDONTWRITEBYTECODE: "1"
    restart: unless-stopped
