services:
  code:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: devcontainer-code
    volumes:
      - ..:/workspaces/e-redes-smart-metering-plus-hass:cached
    command: sleep infinity
    networks:
      - devnet

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2025.6.1
    container_name: hass-dev
    depends_on:
      - code
    ports:
      - "8123:8123"
    volumes:
      - ../config:/config
      - ../custom_components/e_redes_smart_metering_plus:/config/custom_components/e_redes_smart_metering_plus
    environment:
      - TZ=Europe/Lisbon
    restart: unless-stopped
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
