name: Lint

on:
  push:
    branches:
      - feature/*
    paths:
      - '**/*.py'
      - '.github/workflows/lint.yml'
      - 'custom_components/e_redes_smart_metering_plus/manifest.json'
      - 'hacs.json'
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**/*.py'
      - '.github/workflows/lint.yml'
      - 'custom_components/e_redes_smart_metering_plus/manifest.json'
      - 'hacs.json'
      - 'pyproject.toml'
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            requirements_dev.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run black
        run: |
          black --check --diff custom_components/
      - name: Run isort
        run: |
          isort --check-only --diff custom_components/
      - name: Run ruff
        run: |
          ruff check custom_components/

  hacs:
    runs-on: ubuntu-latest
    name: HACS
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
