name: Tests

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Pytest
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: requirements_dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run tests
        run: |
          mkdir -p .reports
          pytest -q \
            --junitxml=.reports/pytest-junit.xml

      - name: Upload test report artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: .reports/
          if-no-files-found: warn
